spring.application.name=visa_bo
spring.config.import=optional:file:.env[.properties]

# Database Connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/visa_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:mitia}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=${SERVER_PORT:2025}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/visa}

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

