spring.application.name=visa_bo

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/visa_db
spring.datasource.username=postgres
spring.datasource.password=mitia
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=2025
server.servlet.context-path=/visa

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
