-- Tables (ordre peu important avec CASCADE)
DROP TABLE IF EXISTS statut_demande CASCADE;
DROP TABLE IF EXISTS check_piece CASCADE;
DROP TABLE IF EXISTS demande CASCADE;
DROP TABLE IF EXISTS visa CASCADE;
DROP TABLE IF EXISTS carte_residence CASCADE;
DROP TABLE IF EXISTS visa_transformable CASCADE;
DROP TABLE IF EXISTS passport CASCADE;
DROP TABLE IF EXISTS demandeur CASCADE;
DROP TABLE IF EXISTS piece CASCADE;
DROP TABLE IF EXISTS type_visa CASCADE;
DROP TABLE IF EXISTS categorie_demande CASCADE;
DROP TABLE IF EXISTS statut CASCADE;
DROP TABLE IF EXISTS nationalite CASCADE;
DROP TABLE IF EXISTS situation_famille CASCADE;
DROP TABLE IF EXISTS champs CASCADE;

-- Séquences
DROP SEQUENCE IF EXISTS seq_demande CASCADE;
DROP SEQUENCE IF EXISTS seq_demandeur CASCADE;
DROP SEQUENCE IF EXISTS seq_passport CASCADE;
DROP SEQUENCE IF EXISTS seq_visa CASCADE;
DROP SEQUENCE IF EXISTS seq_carte_residence CASCADE;
DROP SEQUENCE IF EXISTS seq_visa_transformable CASCADE;
DROP SEQUENCE IF EXISTS seq_type_visa CASCADE;
DROP SEQUENCE IF EXISTS seq_categorie_demande CASCADE;
DROP SEQUENCE IF EXISTS seq_statut CASCADE;
DROP SEQUENCE IF EXISTS seq_nationalite CASCADE;
DROP SEQUENCE IF EXISTS seq_situation_famille CASCADE;
DROP SEQUENCE IF EXISTS seq_piece CASCADE;
DROP SEQUENCE IF EXISTS seq_champs CASCADE;
DROP SEQUENCE IF EXISTS seq_statut_demande CASCADE;